"""films table

Revision ID: 1a49be602f45
Revises: 
Create Date: 2020-04-08 18:40:03.702910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a49be602f45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('plot', sa.String(), nullable=True),
    sa.Column('releasedate', sa.DateTime(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('actors', sa.String(), nullable=True),
    sa.Column('rating', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film')
    # ### end Alembic commands ###
